force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <label>Animal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Eats__c.field-meta.xml
<CustomField>
    <fullName>Eats__c</fullName>
    <label>Eats</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <label>External Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Says__c.field-meta.xml
<CustomField>
    <fullName>Says__c</fullName>
    <label>Says</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FutureAnimalCallout.cls
global class FutureAnimalCallout {
    
    @future(callout = true)
    public static void doAnimalRESTCallout(List<Integer> externalId) {
        
        Map<Integer,AnimalResponse> resultMap = AnimalRESTCallout.getAnimals(externalId);
        
        List<Animal__c> animalsToUpdate = [SELECT External_Id__c,Name, Eats__c, Says__c FROM Animal__c WHERE External_Id__c IN : resultMap.keySet()];
        for(Animal__c animal : animalsToUpdate) {
            AnimalResponse response = resultMap.get(animal.External_Id__c.intValue());
            animal.Eats__c = response.animal.eats;
            animal.Says__c = response.animal.says;
            animal.Name = response.animal.name;
        } 
        
        update animalsToUpdate;
    }
}