force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <label>Animal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <label>External Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AnimalTriggerHandler.cls
public class AnimalTriggerHandler {
	List<Animal__c> newList = new List<Animal__c>();
    
    public AnimalTriggerHandler(List<Animal__c> newList) {
        this.newList = newList;
    }
    
    public void afterInsert() {
        List<Integer> externalId = new List<Integer>();
        for (Animal__c animal : newList) {
            externalId.add(animal.External_Id__c.intValue());
        }
        FutureAnimalCallout.doAnimalRESTCallout(externalId);
    }
}