force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <label>Animal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Eats__c.field-meta.xml
<CustomField>
    <fullName>Eats__c</fullName>
    <label>Eats</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Says__c.field-meta.xml
<CustomField>
    <fullName>Says__c</fullName>
    <label>Says</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AnimalResponse.cls
public class AnimalResponse {   
	public AnimalData animal;
    
    public class AnimalData {
		public Integer id;	
		public String name;	
		public String eats;	
		public String says;	
	}  
    
    public static Animal__c getAnimal(String JSONString) {
        AnimalResponse response = (AnimalResponse) JSON.deserialize(JSONString, AnimalResponse.class);
        Animal__c animal = new Animal__c();
        animal.Eats__c = response.animal.eats;
        animal.Says__c = response.animal.says;
        animal.Name = response.animal.name;
        return animal;
    }
}