force-app/main/default/objects/Author__c/Author__c.object-meta.xml
<CustomObject>
    <label>Author</label>
    <nameField>
        <label>Аuthor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Author__c/fields/Number_of_children__c.field-meta.xml
<CustomField>
    <fullName>Number_of_children__c</fullName>
    <label>Number of children</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MyBatchClass.cls
public class MyBatchClass implements Database.Batchable<sObject>, Schedulable{
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'Select Author__c From Book__c'
        );
    }
    
    public void execute(SchedulableContext ctx) {
        Database.executeBatch(new MyBatchClass());
    }
    
    public void execute(Database.BatchableContext bc, List<Book__c> books){
        Map<Id,Integer> numberOfChildren = new Map<Id, Integer>(); 
        for (Book__c b : books) {
            Id authorId = b.Author__c;
            if (numberOfChildren.containsKey(authorId)) {
                Integer amount = numberOfChildren.get(authorId) + 1;
                numberOfChildren.put(authorId,amount);
            } else {
                numberOfChildren.put(authorId,1);
            }
        } 
        List<Author__c> authors = [Select Number_of_children__c From Author__c Where Id In : numberOfChildren.keySet()];  
        for(Author__c a : authors) {
            a.Number_of_children__c = numberOfChildren.get(a.Id);
        }
        update authors;
    }
    
    public void finish(Database.BatchableContext bc){}
}