force-app/main/default/objects/Author__c/Author__c.object-meta.xml
<CustomObject>
    <label>Author</label>
    <nameField>
        <label>Аuthor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
    public static List<Author__c> createAuthors(Integer numberOfAuthors) {
        List<Author__c> authors = new List<Author__c>();
        for (Integer i = 0; i < numberOfAuthors; i++) {
            Author__c author = new Author__c(Name = 'TestAuthor' + i);
            authors.add(author);
        }
        insert authors;
        return authors;
    }
    
    public static List<Book__c> createBooks(Integer numberOfBooks) {
        List<Book__c> books = new List<Book__c>();
        for (Integer i = 0; i < numberOfBooks; i++) {
            Book__c book = new 	Book__c(Name = 'TestBook' + i);
            books.add(book);
        }
        return books;
    }
}