force-app/main/default/objects/Author__c/Author__c.object-meta.xml
<CustomObject>
    <label>Author</label>
    <nameField>
        <label>Аuthor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/BookTriggerHelper.cls
public class BookTriggerHelper {

    public static List<Author__c> updateParentDateAndTime(List<Book__c> books) {
        Set<String> authors = new Set<String>();
        for (Book__c b : books) {
            authors.add(b.Author__c);
        }
        List<Author__c> authorsToUpdate = [Select Name,Date_and_Time__c From Author__c Where Id In : authors];
        return setDateAndTime(authorsToUpdate);
    }

    public static List<Author__c> setDateAndTime(List<Author__c> authors) {
        List<Author__c> result = new List<Author__c>();
        for(Author__c a : authors) {
            a.Date_and_Time__c = Datetime.now();
        	result.add(a);
    	}
        return result;
    }
}