force-app/main/default/objects/Author__c/Author__c.object-meta.xml
<CustomObject>
    <label>Author</label>
    <nameField>
        <label>Аuthor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Publisher__c/Publisher__c.object-meta.xml
<CustomObject>
    <label>Publisher</label>
    <nameField>
        <label>Publisher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publishers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestBookTrigger.cls
@isTest
public class TestBookTrigger {    
     @isTest static void TestUpdateAuthorDateTimeField() {
        Integer numberOfBooksAndAuthors = 50;
        Publisher__c publisher = new Publisher__c(Name = 'TestPublisher');
        insert publisher;
         
        List<Author__c> authors = TestDataFactory.createAuthors(numberOfBooksAndAuthors);
        List<Book__c> books = TestDataFactory.createBooks(numberOfBooksAndAuthors);
        List<Book__c> booksForInsert = new List<Book__c>();
         
        for(Integer i = 0; i < numberOfBooksAndAuthors; i++) {
            Book__c book = books.get(i);
            book.Publisher__c = publisher.Id; 
            book.Author__c = authors.get(i).Id;
            booksForInsert.add(book);
         } 
         
       Test.startTest();
       Database.SaveResult[]  results = Database.insert(booksForInsert);
       Test.stopTest();
         
       List<Author__c> updatedAuthors = [Select Date_and_Time__c From Author__c Where Id In : authors];
         
       for(Integer i = 0; i < results.size(); i++) {
           System.assert(results[i].isSuccess());
           System.assertEquals(Datetime.now(),updatedAuthors[i].Date_and_Time__c);
       }  
    }
}