force-app/main/default/objects/Author__c/Author__c.object-meta.xml
<CustomObject>
    <label>Author</label>
    <nameField>
        <label>Аuthor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Author__c/fields/Number_of_children__c.field-meta.xml
<CustomField>
    <fullName>Number_of_children__c</fullName>
    <label>Number of children</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Publisher__c/Publisher__c.object-meta.xml
<CustomObject>
    <label>Publisher</label>
    <nameField>
        <label>Publisher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publishers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MyBatchClassTest.cls
@isTest
public class MyBatchClassTest {
    @testSetup static void testSetup() {
        Author__c author = new Author__c(Name = 'BatchTestAuthor');
        Publisher__c publisher = new Publisher__c(Name = 'BatchTestPublisher');
        insert author;
        insert publisher;
        List<Book__c> books = new List<Book__c>();
        for(Integer i = 0; i < 2; i++) {
            Book__c book = new Book__c(Name = 'BatchTestBook' + i);
            book.Author__c = author.Id;
            book.Publisher__c = publisher.Id;
            books.add(book);
        }   
        insert books;
    }
    
    @isTest public static void testSchedulerWork() {
        Test.startTest();
        MyBatchClass batch = new MyBatchClass();
        String sch = '0 0 0 18 2 ? 2024';
        String jobID = System.schedule('Scheduler', sch, batch);
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
        System.assertEquals(0, ct.TimesTriggered); 
        System.assertEquals('2024-02-18 00:00:00', String.valueOf(ct.NextFireTime));   
        Test.stopTest();
    }
    
    @isTest public static void testBatchWork() {
        MyBatchClass batch = new MyBatchClass();
        Test.startTest();
        Id batchId = Database.executeBatch(batch);
        Test.stopTest();
        Author__c author = [Select Name,Number_of_children__c From Author__c Where Name = 'BatchTestAuthor' Limit 1];
        System.assertEquals(2, author.Number_of_children__c);
    }
}