force-app/main/default/objects/Author__c/Author__c.object-meta.xml
<CustomObject>
    <label>Author</label>
    <nameField>
        <label>Аuthor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/First_Published__c.field-meta.xml
<CustomField>
    <fullName>First_Published__c</fullName>
    <label>First Published</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Publisher__c/Publisher__c.object-meta.xml
<CustomObject>
    <label>Publisher</label>
    <nameField>
        <label>Publisher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publishers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BookController.cls
public class BookController {
    public String bookName {get; set;}
    public String bookFirstPublished {get; set;}
    public String bookGenre {get; set;}
    public String bookAuthor {get; set;}
    public String bookPublisherName {get; set;}
    
    public BookController() {
        Book__c book = [SELECT Name, First_Published__c, Genre__c, Author__r.Name, Publisher__r.Name FROM Book__c 
                				WHERE id =: ApexPages.currentPage().getParameters().get('id') ];
		bookName = book.Name;
        bookFirstPublished = String.valueOf(book.First_Published__c);
        bookGenre = book.Genre__c;
        bookAuthor = book.Author__r.Name;
        bookPublisherName = book.Publisher__r.Name; 
    }
}