force-app/main/default/objects/Author__c/Author__c.object-meta.xml
<CustomObject>
    <label>Author</label>
    <nameField>
        <label>Аuthor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Publisher__c/Publisher__c.object-meta.xml
<CustomObject>
    <label>Publisher</label>
    <nameField>
        <label>Publisher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publishers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/QueueableParent.cls
public class QueueableParent implements Queueable{
    private String authorName;
    private String publisherName;
    private String bookName;
    private Id authorId;
    private Id publisherId;
      
    public QueueableParent(String authorName, String publisherName,String bookName) {
        this.authorName = authorName;
        this.publisherName = publisherName;
        this.bookName = bookName;
    }
    
    public QueueableParent(Id authorId, Id publisherId,String bookName) {
        this.authorId = authorId;
        this.publisherId = publisherId;
        this.bookName = bookName;
    }
    
    public void execute(QueueableContext context) {
        if (authorId == null && publisherId == null) {
            Author__c author = new Author__c(Name = authorName);
            Publisher__c publisher = new Publisher__c(Name = publisherName);
            
            insert publisher;
            insert author;
            
            System.debug(publisher.name);
            System.debug(author.name);
   
            System.enqueueJob(new QueueableParent(author.id,publisher.id,bookName));
        } else if(authorId != null && publisherId != null) { 
            Book__c book = new Book__c(Name = bookName, Author__c = authorId, Publisher__c = publisherId);
            insert book;
            
            System.debug(book.name);
        }
    }
}